### PR TITLE
Opacity Canvas - Values and Units

### PR DESCRIPTION
**Pull request by kmilo9999**
solves #34

### CODE REVIEW

**Review by mcmcgrath13 — APPROVED** [review]
Great progress here!

**Comment by kmilo9999** [comment]
@RobertGemmaJr quick check please!

**Review by RobertGemmaJr — APPROVED** [review]
I think it's ready to go! How much more work is there to get the canvas to be fully dynamic? Great work 😄

**Comment by kmilo9999** [comment]
@RobertGemmaJr let's talk about it in #66 . I already started, but it seems that I am missing some data to make it fully dynamic.

**Pull request merged**
